### ISSUE TITLE
Choosing p_cut from volcano plot

### ISSUE THREAD

**Issue by pakiessling** [BradBalderson/Cytocipher#2]
Thanks for the tool, looks very promising.

I am trying it out for my data and the volcano plot looks like this for p=0.045:

![grafik](https://github.com/BradBalderson/Cytocipher/assets/104848590/b9d6839d-3a70-4cf7-b0d6-7196bca56693)
 
I got more cells with - log-FC than in your Pancreas example.

Does this suggest I should decrease my p_cut (by some orders of magnitude) to remove most of the negativ log-FC? 

p_cut = 0.00045

![grafik](https://github.com/BradBalderson/Cytocipher/assets/104848590/4d306f38-123b-4ef2-ae54-c674cd7019f7)

**Comment by BradBalderson** [comment]
Hi @pakiessling,

The volcano plot is informative to an extent, to atleast make sure how log-FC is reflecting cluster pair significance. But I think the enrichment heatmap for the unmerged versus merged data is more informative. 

I am wondering what this looks like? E.g. code below:

`cc.pl.enrich_heatmap(data, 'leiden_merged', figsize=(4,4), scale_cols=True)`

**Comment by pakiessling** [comment]
p_cut=0.00045 , 15 markers

Before merge:
![grafik](https://github.com/BradBalderson/Cytocipher/assets/104848590/39378e65-83a8-42a4-966d-627e4ce02156)

After merge:
![grafik](https://github.com/BradBalderson/Cytocipher/assets/104848590/ce1b8dbe-4784-454b-8478-b1576914e56d)

![grafik](https://github.com/BradBalderson/Cytocipher/assets/104848590/622bd0ff-23f0-4ba3-9231-7a407c58c506)


I think I actually like what it did, just have to look more into the huge cluster 14

**Comment by BradBalderson** [comment]
I think n_markers is way too high for code-scoring. Please try with 5-8. I think the above is dramatically under-clustered with those parameters.

**Comment by pakiessling** [comment]
Thank you, I started with the default amount of marker genes, but it kept forcing me to increase the amount of markers becuase of identical patterns in clusters

**Comment by BradBalderson** [comment]
Ah right, sorry about this, that warning is actually not really an issue, and can be safely ignored. 

Another user mentioned this in the first issue, and I have correct it on the github main branch, but haven't yet updated the pip version. 

Could we try with the lower number of marker genes anyhow?

**Comment by pakiessling** [comment]
Looks much more reasonable with lower markers and also cleaning the data more beforehand
